import { dependency } from './runtime.mjs';
import { fileURLToPath } from 'node:url';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { action, settle, ready, amount, cut, take, whole, fulfill, requests, simplify, chooseLanguage } from './driver.mjs';
const { chromium } = dependency('playwright'), sharp = dependency('sharp');
const output = new URL('../.checks/', import.meta.url);
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const errors = [], failures = [];
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.addInitScript(() => {
  let seed = 123456;
  Math.random = () => { seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0; return seed / 4294967296; };
});
page.on('pageerror', (error) => errors.push(error.message));
page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });
page.on('response', (response) => { if (response.status() >= 400) failures.push(response.url()); });
const snapshot = (name) => page.screenshot({ path: fileURLToPath(new URL(name + '.png', output)), fullPage: true });
async function checkCanvas(name) {
  const buffer = await page.locator('canvas').screenshot();
  const { data, info } = await sharp(buffer).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  const colors = new Set();
  for (let i = 0; i < data.length; i += info.channels * 37) colors.add([data[i] >> 3, data[i + 1] >> 3, data[i + 2] >> 3].join(':'));
  assert.ok(colors.size > 100, name + ': blank canvas');
  console.log(name + ': ' + colors.size + ' quantized colors');
}
try {
  await page.goto('http://localhost:5173/sampleminigame/');
  await page.waitForFunction(() => document.querySelector('canvas').dataset.props === '6');
  await chooseLanguage(page, 'en');
  await settle(page); await checkCanvas('Whole cakes');
  const firstTicket = JSON.stringify(await requests(page));
  await cut(page, 'chocolate', 12);
  await page.mouse.click(285, 480); await settle(page);
  assert.deepEqual(await amount(page, 'chocolate'), [1, 12]);
  await take(page, 2, 1);
  await simplify(page, 'chocolate', 3);
  assert.deepEqual(await amount(page, 'chocolate'), [1, 4]);
  await snapshot('merged');
  await action(page, 'return', 'chocolate').click(); await settle(page);
  assert.equal((await amount(page, 'chocolate'))[0], 0);
  await cut(page, 'lemon', 3); await take(page, 1);
  await cut(page, 'chocolate', 4); await take(page, 1);
  await cut(page, 'chocolate', 2);
  assert.equal((await amount(page, 'chocolate'))[0], 0);
  assert.deepEqual(await amount(page, 'lemon'), [1, 3]);
  await action(page, 'clear').click(); await settle(page);
  await whole(page, 3); await cut(page, 'chocolate', 12); await take(page, 3);
  assert.deepEqual(await amount(page, 'chocolate'), [39, 12]);
  await simplify(page, 'chocolate', 3);
  assert.deepEqual(await amount(page, 'chocolate'), [13, 4]);
  await action(page, 'return', 'chocolate').last().click(); await settle(page);
  assert.deepEqual(await amount(page, 'chocolate'), [3, 1]);
  await cut(page, 'chocolate', 12); await take(page, 1);
  await action(page, 'flavor', 'lemon').click(); await settle(page); await whole(page, 2);
  await cut(page, 'lemon', 6); await take(page, 1);
  assert.equal(await page.locator('#plate-counter').textContent(), '7 / 7 plates');
  await snapshot('seven-plates');
  for (const width of [320, 390, 740, 768, 1024]) {
    await page.setViewportSize({ width, height: 844 }); await settle(page);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Overflow at ' + width);
    await checkCanvas('Viewport ' + width); await snapshot('viewport-' + width);
  }
  await page.setViewportSize({ width: 1024, height: 720 }); await settle(page);
  const tray = await page.locator('.serving').boundingBox(), delivery = await page.locator('.delivery').boundingBox();
  assert.ok(tray.y + tray.height < delivery.y, 'Tray overlaps delivery');
  await cut(page, 'cheesecake', 4); await take(page, 1);
  assert.equal((await amount(page, 'cheesecake'))[0], 0);
  assert.match(await page.locator('#message').textContent(), /seven/);
  await action(page, 'return', 'chocolate').first().click(); await settle(page);
  assert.equal(await page.locator('#plate-counter').textContent(), '6 / 7 plates');
  await action(page, 'clear').click(); await settle(page);
  await page.setViewportSize({ width: 1440, height: 900 });
  for (let i = 0; i < 6; i++) {
    assert.ok((await requests(page)).every(({ numerator, denominator }) => numerator % denominator !== 0));
    await fulfill(page);
    if (i === 5) await snapshot('final-order');
    await action(page, 'serve').click();
    await page.waitForFunction((index) => document.querySelector('#guest-counter').textContent === index + ' / 6 guests', i + 1);
    await ready(page); await settle(page);
  }
  assert.equal(await page.locator('#ending').isVisible(), true); await snapshot('ending');
  await page.locator('#ending [data-action="replay"]').click(); await settle(page);
  assert.notEqual(JSON.stringify(await requests(page)), firstTicket);
  assert.equal(await page.locator('#plate-counter').textContent(), '0 / 7 plates');
  await page.locator('#piece-count').fill('13'); await action(page, 'cut').click();
  assert.equal(await page.locator('#piece-count').evaluate((input) => input.checkValidity()), false);
  await action(page, 'flavor', 'chocolate').click();
  await page.locator('#piece-count').fill('4'); await page.locator('#piece-count').press('Enter'); await settle(page);
  await page.locator('[data-action="take"][data-id="0"]').focus(); await page.keyboard.press('Enter');
  assert.equal(await page.locator('[data-action="take"][data-id="1"]').evaluate((button) => button === document.activeElement), true);
  await page.keyboard.press('Enter'); await settle(page);
  assert.deepEqual(await amount(page, 'chocolate'), [2, 4]); await snapshot('desktop');
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.reload();
  await page.waitForFunction(() => document.querySelector('canvas').dataset.props === '6');
  await chooseLanguage(page, 'en');
  await fulfill(page); await action(page, 'serve').click();
  await page.waitForFunction(() => document.querySelector('#guest-counter').textContent === '1 / 6 guests');
  console.log('Random six-guest session, mixed cakes, capacity, equivalent fractions, merge/undo, recut, keyboard, replay, reduced motion: PASS');
  console.log('Errors:', errors, 'Failed resources:', failures);
  assert.deepEqual(errors, []); assert.deepEqual(failures, []);
} finally { await browser.close(); }
