import { dependency } from './runtime.mjs';
import { mkdir } from 'node:fs/promises';
const { chromium } = dependency('playwright');
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });
await mkdir(new URL('../.checks/', import.meta.url), { recursive: true });
await page.goto('http://localhost:5173/sampleminigame/');
await page.waitForFunction(() => document.querySelector('canvas').dataset.props !== undefined);
await page.waitForTimeout(1200);
console.log('Props:', await page.locator('canvas').getAttribute('data-props'), 'Errors:', errors);
await page.screenshot({ path: new URL('../.checks/desktop.png', import.meta.url).pathname.replace(/^\//, ''), fullPage: true });
await page.locator('#piece-count').fill('12');
await page.locator('[data-action="cut"]').click();
await page.waitForTimeout(900);
await page.screenshot({ path: new URL('../.checks/cut.png', import.meta.url).pathname.replace(/^\//, ''), fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(500);
await page.screenshot({ path: new URL('../.checks/mobile.png', import.meta.url).pathname.replace(/^\//, ''), fullPage: true });
await browser.close();
